#!/bin/bash

SESSION_NAME=''

if [[ $1 = "-s" ]] && [[ $2 != "" ]]; then
	SESSION_NAME="$2";
fi

if [[ $SESSION_NAME = "" ]]; then
	tmux new-session \; split-window -v \; select-pane -U \; split-window -h \; select-pane -L \; attach
else
	tmux new-session -s "$SESSION_NAME" \; split-window -v \; select-pane -U \; split-window -h \; select-pane -L \; attach
fi
